version: "3"

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    image: wwf
    container_name: wwf
    env_file:
      - ./.envs/.production/.flask
    expose:
      - 80
    ports:
      - "127.0.0.1:5000:80"
    restart: always
